*
!package.json
!yarn.lock
!pyproject.toml

!frontend/
frontend/*
!frontend/package.json

!e2e/
e2e/*
!e2e/package.json
!e2e/yarn.lock

!suite/
suite/*
!suite/suite_meet/
suite/suite_meet/*
!suite/suite_meet/sfu-server/
suite/suite_meet/sfu-server/*
!suite/suite_meet/sfu-server/package.json
!suite/suite_meet/sfu-server/yarn.lock
